@preconcurrency import AVFoundation
import Foundation
import Sodium
import UIKit

enum MediaPipelineError: Error, LocalizedError {
    case recordingNotWired
    case invalidRawRecordingSource
    case exportSessionUnavailable
    case exportFailed
    case exportCancelled
    case playbackPreparationInvalidated
    case plaintextProductionInvalidated
    case stagedPackageMissing
    case localPackageCollision(UUID)
    case invalidAuthenticatedThumbnailIdentifier
    case cryptoOperationFailed(String)

    var errorDescription: String? {
        switch self {
        case .recordingNotWired:
            return "The AVFoundation recording session has not been wired yet."
        case .invalidRawRecordingSource:
            return "The captured video is unavailable or is not a regular file. Record the video again."
        case .exportSessionUnavailable:
            return "AVFoundation could not create a video export session."
        case .exportFailed:
            return "The video export failed."
        case .exportCancelled:
            return "The video export was cancelled."
        case .playbackPreparationInvalidated:
            return "Playback preparation stopped because Kithra is no longer active."
        case .plaintextProductionInvalidated:
            return "Media preparation stopped because Kithra is no longer active."
        case .stagedPackageMissing:
            return "The staged media package is no longer available."
        case .localPackageCollision(let messageID):
            return "An encrypted local package already exists for message \(messageID.uuidString)."
        case .invalidAuthenticatedThumbnailIdentifier:
            return "The local thumbnail identifier is not bound to a valid authenticated envelope signature."
        case .cryptoOperationFailed(let operation):
            return "\(operation) failed."
        }
    }
}

struct PlaintextTemporaryFileCleanupError: Error, LocalizedError {
    let failedPaths: [String]

    var errorDescription: String? {
        "Kithra could not delete plaintext temporary media: \(failedPaths.joined(separator: ", "))."
    }
}

struct KithraPlaintextCleanupReport: Equatable {
    var removedFiles: [URL] = []
    var failedFiles: [URL] = []
    var activeFiles: [URL] = []
}

/// Removes only plaintext temporary artifacts whose names are generated by
/// Kithra. The allowlist is deliberately UUID-shaped and non-recursive so a
/// cleanup pass cannot remove another framework's temporary files or encrypted
/// message staging.
final class KithraPlaintextTempFileJanitor: @unchecked Sendable {
    static let shared = KithraPlaintextTempFileJanitor()

    private let lock = NSLock()
    private var retainedPaths: Set<String> = []
    private var producerCountsByPath: [String: Int] = [:]
    private var isClosedForAccountDeletion = false

    /// Reserves an exact plaintext output before any producer can create or
    /// write it. Closing the account-deletion barrier and reserving a path use
    /// the same lock, so a producer can never appear in the final-sweep gap.
    func preserveWhileInUse(_ url: URL) throws {
        lock.lock()
        guard !isClosedForAccountDeletion else {
            lock.unlock()
            throw MediaPipelineError.plaintextProductionInvalidated
        }
        retainedPaths.insert(canonicalPath(for: url))
        lock.unlock()
    }

    /// Registers destinations whose producer may still create or recreate the
    /// file. Retained ownership can be released by an early unlink, but this
    /// producer reservation survives until the definitive completion or
    /// cancellation callback calls `finishProducing`.
    func beginProducing(_ urls: [URL]) throws {
        let paths = urls.map(canonicalPath(for:))
        lock.lock()
        guard !isClosedForAccountDeletion else {
            lock.unlock()
            throw MediaPipelineError.plaintextProductionInvalidated
        }
        retainedPaths.formUnion(paths)
        for path in paths {
            producerCountsByPath[path, default: 0] += 1
        }
        lock.unlock()
    }

    func finishProducing(_ urls: [URL]) {
        let paths = urls.map(canonicalPath(for:))
        lock.lock()
        for path in paths {
            let remaining = (producerCountsByPath[path] ?? 0) - 1
            if remaining > 0 {
                producerCountsByPath[path] = remaining
            } else {
                producerCountsByPath[path] = nil
            }
        }
        lock.unlock()
    }

    func release(_ url: URL) {
        lock.lock()
        retainedPaths.remove(canonicalPath(for: url))
        lock.unlock()
    }

    func closeForAccountDeletion() {
        lock.lock()
        isClosedForAccountDeletion = true
        lock.unlock()
    }

    func reopenAfterAccountDeletionEnds() {
        lock.lock()
        isClosedForAccountDeletion = false
        lock.unlock()
    }

    var accountDeletionBarrierIsClosed: Bool {
        lock.lock()
        defer { lock.unlock() }
        return isClosedForAccountDeletion
    }

    static func ownsPlaintextFile(
        _ url: URL,
        applicationTemporaryRoot: URL,
        mediaTemporaryRoot: URL
    ) -> Bool {
        let canonicalURL = url.standardizedFileURL
        if ownsInlineRecordingFile(
            canonicalURL,
            applicationTemporaryRoot: applicationTemporaryRoot
        ) {
            return true
        }
        let parent = canonicalURL.deletingLastPathComponent()
        if parent == mediaTemporaryRoot.standardizedFileURL {
            return isMediaPlaintextFile(canonicalURL.lastPathComponent)
        }
        return false
    }

    static func ownsInlineRecordingFile(
        _ url: URL,
        applicationTemporaryRoot: URL
    ) -> Bool {
        let canonicalURL = url.standardizedFileURL
        return canonicalURL.deletingLastPathComponent()
            == applicationTemporaryRoot.standardizedFileURL
            && isInlineRecordingFile(canonicalURL.lastPathComponent)
    }

    @discardableResult
    func cleanupAbandonedFiles(
        fileManager: FileManager = .default,
        applicationTemporaryRoot: URL,
        mediaTemporaryRoot: URL
    ) -> KithraPlaintextCleanupReport {
        var report = KithraPlaintextCleanupReport()
        cleanupDirectChildren(
            of: applicationTemporaryRoot,
            fileManager: fileManager,
            matches: Self.isInlineRecordingFile,
            report: &report
        )
        cleanupDirectChildren(
            of: mediaTemporaryRoot,
            fileManager: fileManager,
            matches: Self.isMediaPlaintextFile,
            report: &report
        )
        // AVFoundation may have accepted a destination but not created it yet.
        // Include every owned reservation, even when no directory entry was
        // visible to either scan. Account deletion cannot proceed until its
        // definitive completion/cancellation path releases that reservation.
        lock.lock()
        let reservedURLs = retainedPaths.union(producerCountsByPath.keys)
            .map { URL(fileURLWithPath: $0) }
        lock.unlock()
        let reportedActivePaths = Set(report.activeFiles.map { canonicalPath(for: $0) })
        report.activeFiles.append(contentsOf: reservedURLs.filter { url in
            Self.ownsPlaintextFile(
                url,
                applicationTemporaryRoot: applicationTemporaryRoot,
                mediaTemporaryRoot: mediaTemporaryRoot
            ) && !reportedActivePaths.contains(canonicalPath(for: url))
        })
        return report
    }

    private func cleanupDirectChildren(
        of root: URL,
        fileManager: FileManager,
        matches: (String) -> Bool,
        report: inout KithraPlaintextCleanupReport
    ) {
        guard fileManager.fileExists(atPath: root.path) else {
            return
        }

        let children: [URL]
        do {
            children = try fileManager.contentsOfDirectory(
                at: root,
                includingPropertiesForKeys: [.isRegularFileKey, .isSymbolicLinkKey],
                options: [.skipsHiddenFiles]
            )
        } catch {
            report.failedFiles.append(root)
            return
        }

        for child in children where matches(child.lastPathComponent) {
            do {
                let values = try child.resourceValues(forKeys: [
                    .isRegularFileKey,
                    .isSymbolicLinkKey
                ])
                guard values.isRegularFile == true, values.isSymbolicLink != true else {
                    continue
                }
            } catch {
                report.failedFiles.append(child)
                continue
            }

            lock.lock()
            let childPath = canonicalPath(for: child)
            let isActive = retainedPaths.contains(childPath)
                || producerCountsByPath[childPath] != nil
            if isActive {
                report.activeFiles.append(child)
            } else {
                do {
                    try fileManager.removeItem(at: child)
                    report.removedFiles.append(child)
                } catch {
                    report.failedFiles.append(child)
                }
            }
            lock.unlock()
        }
    }

    private static func isInlineRecordingFile(_ name: String) -> Bool {
        matchesUUIDFile(name, prefix: "kithra-inline-merged-", extension: "mov")
            || matchesUUIDFile(name, prefix: "kithra-inline-", extension: "mov")
    }

    private static func isMediaPlaintextFile(_ name: String) -> Bool {
        matchesUUIDFile(name, prefix: "raw-", extension: "mov")
            || matchesUUIDFile(name, prefix: "delivery-", extension: "mp4")
            || matchesUUIDFile(name, prefix: "playback-", extension: "mp4")
            || matchesUUIDFile(name, prefix: "thumbnail-staged-", extension: "jpg")
            || matchesAuthenticatedThumbnailFile(name)
    }

    private static func matchesAuthenticatedThumbnailFile(_ name: String) -> Bool {
        let url = URL(fileURLWithPath: name)
        guard url.pathExtension == "jpg" else {
            return false
        }

        let stem = url.deletingPathExtension().lastPathComponent
        for prefix in ["thumb-outgoing-client-", "thumb-incoming-server-"] {
            guard stem.hasPrefix(prefix) else {
                continue
            }

            let remainder = String(stem.dropFirst(prefix.count))
            guard remainder.count == 36 + "-auth-".count + 128 else {
                continue
            }
            let identifierEnd = remainder.index(remainder.startIndex, offsetBy: 36)
            let identifier = String(remainder[..<identifierEnd])
            let authenticatedSuffix = remainder[identifierEnd...]
            guard UUID(uuidString: identifier) != nil,
                  authenticatedSuffix.hasPrefix("-auth-") else {
                continue
            }

            let signatureHex = authenticatedSuffix.dropFirst("-auth-".count)
            return signatureHex.unicodeScalars.allSatisfy { scalar in
                (scalar.value >= 48 && scalar.value <= 57)
                    || (scalar.value >= 97 && scalar.value <= 102)
            }
        }
        return false
    }

    private static func matchesUUIDFile(
        _ name: String,
        prefix: String,
        extension expectedExtension: String
    ) -> Bool {
        let url = URL(fileURLWithPath: name)
        guard url.pathExtension == expectedExtension else {
            return false
        }
        let stem = url.deletingPathExtension().lastPathComponent
        guard stem.hasPrefix(prefix) else {
            return false
        }
        let identifier = String(stem.dropFirst(prefix.count))
        return identifier.count == 36 && UUID(uuidString: identifier) != nil
    }

    private func canonicalPath(for url: URL) -> String {
        url.standardizedFileURL.path
    }
}

enum V1MediaLimits {
    static let maximumRecordingDurationSeconds: TimeInterval = 120
    static let maximumEncryptedBlobBytes: Int64 = 64 << 20
}

enum EncryptedMediaUploadPolicyError: Error, LocalizedError, Equatable {
    case invalidFile
    case emptyFile
    case declaredSizeMismatch(declared: Int, actual: Int64)
    case blobTooLarge(actual: Int64, maximum: Int64)

    var errorDescription: String? {
        switch self {
        case .invalidFile:
            return "The encrypted video file is unavailable or is not a regular file. Record the video again."
        case .emptyFile:
            return "The encrypted video file is empty. Record the video again."
        case .declaredSizeMismatch(let declared, let actual):
            return "The encrypted video changed before upload (expected \(declared) bytes, found \(actual)). Record the video again."
        case .blobTooLarge(let actual, let maximum):
            let actualMiB = Double(actual) / Double(1 << 20)
            let maximumMiB = Double(maximum) / Double(1 << 20)
            return String(
                format: "The encrypted video is %.1f MiB; Kithra V1 supports at most %.0f MiB. Record a shorter video or choose 480p.",
                actualMiB,
                maximumMiB
            )
        }
    }
}

enum EncryptedMediaUploadPolicy {
    @discardableResult
    static func validate(
        fileURL: URL,
        declaredBlobSize: Int,
        maximumBytes: Int64 = V1MediaLimits.maximumEncryptedBlobBytes
    ) throws -> Int64 {
        let values = try fileURL.resourceValues(forKeys: [
            .isRegularFileKey,
            .isSymbolicLinkKey,
            .fileSizeKey
        ])
        guard values.isRegularFile == true,
              values.isSymbolicLink != true,
              let fileSize = values.fileSize else {
            throw EncryptedMediaUploadPolicyError.invalidFile
        }

        let actualSize = Int64(fileSize)
        guard actualSize > 0 else {
            throw EncryptedMediaUploadPolicyError.emptyFile
        }
        guard actualSize == Int64(declaredBlobSize) else {
            throw EncryptedMediaUploadPolicyError.declaredSizeMismatch(
                declared: declaredBlobSize,
                actual: actualSize
            )
        }
        guard actualSize <= maximumBytes else {
            throw EncryptedMediaUploadPolicyError.blobTooLarge(
                actual: actualSize,
                maximum: maximumBytes
            )
        }
        return actualSize
    }
}

struct RecordingDurationBudget: Equatable {
    let maximumSeconds: TimeInterval
    private(set) var recordedSeconds: TimeInterval = 0

    init(maximumSeconds: TimeInterval = V1MediaLimits.maximumRecordingDurationSeconds) {
        self.maximumSeconds = maximumSeconds
    }

    var remainingSeconds: TimeInterval {
        max(0, maximumSeconds - recordedSeconds)
    }

    mutating func reset() {
        recordedSeconds = 0
    }

    mutating func includeSegment(durationSeconds: TimeInterval) {
        guard durationSeconds.isFinite, durationSeconds > 0 else {
            return
        }
        recordedSeconds = min(maximumSeconds, recordedSeconds + durationSeconds)
    }
}

enum DeliveryVideoQuality: String, Codable, CaseIterable, Identifiable {
    case compact480p
    case standard720p

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .compact480p:
            return "480p"
        case .standard720p:
            return "720p"
        }
    }

    var exportPreset: String {
        switch self {
        case .compact480p:
            return AVAssetExportPresetMediumQuality
        case .standard720p:
            return AVAssetExportPreset1280x720
        }
    }
}

struct RawRecordingConfiguration: Hashable {
    var maxDurationSeconds: TimeInterval = V1MediaLimits.maximumRecordingDurationSeconds
    var quality: DeliveryVideoQuality = .compact480p
    var includeAudio: Bool = true
}

struct EncryptedMediaPackage: Identifiable, Hashable {
    let id: UUID
    var messageID: UUID?
    var envelope: MessageEnvelope
    var encryptedBlobURL: URL
    var localEncryptedCopyURL: URL
    var blobSize: Int
}

/// A hash-validated incoming blob held outside durable message history until
/// the caller has accepted its authenticated replay receipt.
struct StagedReceivedMediaPackage: Identifiable, Hashable {
    let id: UUID
    fileprivate let messageID: UUID
    fileprivate let envelope: MessageEnvelope
}

struct PlaybackTempFile: Identifiable, Hashable {
    let id: UUID
    var url: URL
    var createdAt: Date
    var cleanupDeadline: Date
}

/// A thread-safe, single-use authorization for producing plaintext while the
/// app is active. Output reservation and invalidation share one lock. Active AV
/// operations also register cancellation hooks so backgrounding both cancels
/// work and returns every exact output path for deterministic cleanup.
final class ForegroundPlaintextPermit: @unchecked Sendable {
    let id = UUID()

    private let lock = NSLock()
    private var valid = true
    private var outputURLsByPath: [String: URL] = [:]
    private var cancellationByOperationID: [UUID: @Sendable () -> Void] = [:]

    var isValid: Bool {
        lock.lock()
        defer { lock.unlock() }
        return valid
    }

    func registerOutput(_ url: URL) throws {
        try registerOutputs([url])
    }

    func registerOutputs(_ urls: [URL]) throws {
        lock.lock()
        defer { lock.unlock() }
        guard valid else {
            throw MediaPipelineError.plaintextProductionInvalidated
        }
        for url in urls {
            let canonicalURL = url.standardizedFileURL
            outputURLsByPath[canonicalURL.path] = canonicalURL
        }
    }

    func beginOperation(
        outputURLs: [URL],
        cancellation: @escaping @Sendable () -> Void
    ) throws -> UUID {
        lock.lock()
        defer { lock.unlock() }
        guard valid else {
            throw MediaPipelineError.plaintextProductionInvalidated
        }
        for url in outputURLs {
            let canonicalURL = url.standardizedFileURL
            outputURLsByPath[canonicalURL.path] = canonicalURL
        }
        let operationID = UUID()
        cancellationByOperationID[operationID] = cancellation
        return operationID
    }

    func finishOperation(_ operationID: UUID) {
        lock.lock()
        cancellationByOperationID[operationID] = nil
        lock.unlock()
    }

    /// Starts an already-registered producer while holding the same lock used
    /// by invalidation. Invalidation therefore either prevents the producer
    /// from starting or runs its cancellation hook after start returns; it can
    /// never cancel first and then allow AVFoundation work to start afterward.
    func startOperation(_ operationID: UUID, _ start: () -> Void) -> Bool {
        lock.lock()
        defer { lock.unlock() }
        guard valid, cancellationByOperationID[operationID] != nil else {
            return false
        }
        start()
        return true
    }

    func createOutput<T>(at url: URL, _ body: () throws -> T) throws -> T {
        try createOutputs(at: [url], body)
    }

    func createOutputs<T>(at urls: [URL], _ body: () throws -> T) throws -> T {
        lock.lock()
        defer { lock.unlock() }
        guard valid else {
            throw MediaPipelineError.plaintextProductionInvalidated
        }

        for url in urls {
            let canonicalURL = url.standardizedFileURL
            outputURLsByPath[canonicalURL.path] = canonicalURL
        }
        return try body()
    }

    func invalidate() -> [URL] {
        lock.lock()
        valid = false
        let cancellations = Array(cancellationByOperationID.values)
        cancellationByOperationID.removeAll()
        let outputURLs = Array(outputURLsByPath.values)
        lock.unlock()

        // AVFoundation cancellation callbacks can re-enter client code, so do
        // not invoke them while holding the permit lock.
        cancellations.forEach { $0() }
        return outputURLs
    }
}

typealias PlaybackPreparationPermit = ForegroundPlaintextPermit

/// Direction-specific storage namespaces keep a relay-selected server ID from
/// addressing an outgoing package that was created and named locally.
enum LocalEncryptedMediaIdentifier: Hashable {
    case outgoingClientMessage(UUID)
    case incomingServerMessage(UUID)
}

/// A thumbnail is addressed by its complete authenticated envelope signature,
/// not by a relay-selected server ID. The direction prefix also prevents an
/// incoming relay record from aliasing locally generated outgoing UI state.
struct AuthenticatedThumbnailIdentifier: Hashable {
    enum Authority: Hashable {
        case outgoingClientMessage(UUID)
        case incomingServerMessage(UUID)
    }

    let authority: Authority
    fileprivate let envelopeSignature: Data

    init(authority: Authority, envelopeSignature: Data) throws {
        guard envelopeSignature.count == 64 else {
            throw MediaPipelineError.invalidAuthenticatedThumbnailIdentifier
        }
        self.authority = authority
        self.envelopeSignature = envelopeSignature
    }
}

protocol MediaPipelining {
    func makeRawRecordingURL() throws -> URL
    func stagePickerRecording(
        from pickerURL: URL,
        permit: ForegroundPlaintextPermit
    ) throws -> URL
    func recordRawTemp(configuration: RawRecordingConfiguration) async throws -> URL
    func compressForDelivery(
        rawVideoURL: URL,
        quality: DeliveryVideoQuality,
        permit: ForegroundPlaintextPermit
    ) async throws -> URL
    func makeThumbnail(
        videoURL: URL,
        identifier: AuthenticatedThumbnailIdentifier,
        permit: ForegroundPlaintextPermit
    ) async throws -> URL
    func encryptPackage(
        compressedVideoURL: URL,
        thumbnailURL: URL?,
        recipientEncryptionPublicKey: Data,
        senderUserID: UUID,
        senderDeviceID: UUID,
        senderIdentityDigest: Data,
        recipientUserID: UUID,
        recipientDeviceID: UUID,
        recipientIdentityDigest: Data
    ) async throws -> EncryptedMediaPackage
    func persistOutgoingPackage(
        _ encryptedPackageURL: URL,
        clientMessageID: UUID
    ) async throws -> URL
    func localEncryptedPackageURL(for identifier: LocalEncryptedMediaIdentifier) async -> URL?
    func removeLocalEncryptedPackage(for identifier: LocalEncryptedMediaIdentifier) async throws
    func localThumbnailURL(for identifier: AuthenticatedThumbnailIdentifier) async -> URL?
    func stageReceivedPackage(
        message: Message,
        downloadedBlobURL: URL
    ) async throws -> StagedReceivedMediaPackage
    /// Promotes a stage without replacing durable history. Call only after
    /// the authenticated replay receipt has been accepted.
    func commitStagedReceivedPackage(
        _ stagedPackage: StagedReceivedMediaPackage,
        allowExistingExactRecovery: Bool
    ) async throws -> EncryptedMediaPackage
    /// Removes only the stage derived from this opaque staging token.
    func discardStagedReceivedPackage(_ stagedPackage: StagedReceivedMediaPackage) async
    func validateEncryptedPackage(_ package: EncryptedMediaPackage) async throws
    func decryptForPlayback(
        package: EncryptedMediaPackage,
        permit: PlaybackPreparationPermit
    ) async throws -> PlaybackTempFile
    func removePlaintextTemporaryFiles(_ urls: [URL]) async throws
    func cleanupTemporaryFiles(_ urls: [URL]) async
    func cleanupAbandonedPlaintextTemporaryFiles() async
    func closePlaintextProductionForAccountDeletion()
    func reopenPlaintextProductionAfterAccountDeletionEnds()
    func removeAbandonedPlaintextTemporaryFilesForAccountDeletion() async throws
    func removeAllLocalMedia() async throws
}

extension MediaPipelining {
    func cleanupAbandonedPlaintextTemporaryFiles() async {}
}

final class DefaultMediaPipeline: MediaPipelining {
    private let fileManager: FileManager
    private let keyManager: DeviceKeyManaging
    private let tempRoot: URL
    private let localMediaRoot: URL
    private let incomingStagingRoot: URL
    private let plaintextTempJanitor: KithraPlaintextTempFileJanitor
    private let sodium = Sodium()
    private let messageAuthenticator = MessageEnvelopeAuthenticator()

    init(
        fileManager: FileManager = .default,
        keyManager: DeviceKeyManaging = KeychainDeviceKeyManager(),
        tempRoot: URL? = nil,
        localMediaRoot: URL? = nil,
        plaintextTempJanitor: KithraPlaintextTempFileJanitor = .shared
    ) {
        self.fileManager = fileManager
        self.keyManager = keyManager
        let resolvedTempRoot = tempRoot ?? fileManager.temporaryDirectory
            .appendingPathComponent("SpeakeasyMedia", isDirectory: true)
        let resolvedLocalMediaRoot = localMediaRoot
            ?? (fileManager.urls(for: .applicationSupportDirectory, in: .userDomainMask).first
                ?? fileManager.temporaryDirectory)
                .appendingPathComponent("KithraMedia", isDirectory: true)
        self.tempRoot = resolvedTempRoot
        self.localMediaRoot = resolvedLocalMediaRoot
        self.incomingStagingRoot = resolvedTempRoot
            .appendingPathComponent("IncomingStaging", isDirectory: true)
        self.plaintextTempJanitor = plaintextTempJanitor
    }

    func makeRawRecordingURL() throws -> URL {
        try ensureTempRoot()
        let url = tempRoot
            .appendingPathComponent("raw-\(UUID().uuidString)")
            .appendingPathExtension("mov")
        try plaintextTempJanitor.preserveWhileInUse(url)
        return url
    }

    func stagePickerRecording(
        from pickerURL: URL,
        permit: ForegroundPlaintextPermit
    ) throws -> URL {
        let destinationURL = try makeRawRecordingURL()
        var validatedPickerURL: URL?
        do {
            let canonicalPickerURL = pickerURL.standardizedFileURL
            guard isDescendant(
                canonicalPickerURL.resolvingSymlinksInPath(),
                of: fileManager.temporaryDirectory.standardizedFileURL
                    .resolvingSymlinksInPath()
            ) else {
                throw MediaPipelineError.invalidRawRecordingSource
            }
            let sourceValues = try canonicalPickerURL.resourceValues(forKeys: [
                .isRegularFileKey,
                .isSymbolicLinkKey
            ])
            guard sourceValues.isRegularFile == true,
                  sourceValues.isSymbolicLink != true else {
                throw MediaPipelineError.invalidRawRecordingSource
            }
            validatedPickerURL = canonicalPickerURL

            // Register both the system-produced picker draft and Kithra's
            // destination before moving anything. If the app becomes inactive
            // in the following window, invalidation can enqueue both exact
            // paths and this failure path also deletes the validated source.
            try permit.registerOutputs([canonicalPickerURL, destinationURL])

            try plaintextTempJanitor.beginProducing([destinationURL])
            defer { plaintextTempJanitor.finishProducing([destinationURL]) }
            try permit.createOutput(at: destinationURL) {
                try fileManager.moveItem(at: canonicalPickerURL, to: destinationURL)
                try fileManager.setAttributes(
                    [.protectionKey: FileProtectionType.complete],
                    ofItemAtPath: destinationURL.path
                )
            }
            return destinationURL
        } catch {
            removePlaintextTemporaryFile(destinationURL)
            if let validatedPickerURL {
                removePlaintextTemporaryFile(validatedPickerURL)
            }
            throw error
        }
    }

    func recordRawTemp(configuration: RawRecordingConfiguration) async throws -> URL {
        _ = configuration
        let unusedURL = try makeRawRecordingURL()
        removePlaintextTemporaryFile(unusedURL)
        throw MediaPipelineError.recordingNotWired
    }

    func compressForDelivery(
        rawVideoURL: URL,
        quality: DeliveryVideoQuality,
        permit: ForegroundPlaintextPermit
    ) async throws -> URL {
        try ensureTempRoot()

        let outputURL = tempRoot
            .appendingPathComponent("delivery-\(UUID().uuidString)")
            .appendingPathExtension("mp4")

        if fileManager.fileExists(atPath: outputURL.path) {
            try fileManager.removeItem(at: outputURL)
        }

        let asset = AVURLAsset(url: rawVideoURL)
        guard let exportSession = Self.makeDeliveryExportSession(
            asset: asset,
            presetName: quality.exportPreset,
            outputURL: outputURL
        ) else {
            throw MediaPipelineError.exportSessionUnavailable
        }
        try plaintextTempJanitor.beginProducing([outputURL])
        defer { plaintextTempJanitor.finishProducing([outputURL]) }
        let exportBox = SendableExportSession(exportSession)
        let outputHandle = PlaintextOutputFileHandle(
            fileManager: fileManager,
            plaintextTempJanitor: plaintextTempJanitor
        )
        let operationID: UUID
        do {
            operationID = try permit.beginOperation(
                outputURLs: [outputURL],
                cancellation: { exportBox.session.cancelExport() }
            )
        } catch {
            removePlaintextTemporaryFile(outputURL)
            throw error
        }

        return try await withCheckedThrowingContinuation { continuation in
            let didStart = permit.startOperation(operationID) {
                exportBox.session.exportAsynchronously {
                    permit.finishOperation(operationID)
                    switch exportBox.session.status {
                    case .completed:
                        do {
                            try permit.createOutput(at: outputURL) {
                                try outputHandle.applyCompleteProtection(to: outputURL)
                            }
                            continuation.resume(returning: outputURL)
                        } catch {
                            outputHandle.remove(outputURL)
                            continuation.resume(throwing: error)
                        }
                    case .cancelled:
                        outputHandle.remove(outputURL)
                        continuation.resume(throwing: MediaPipelineError.exportCancelled)
                    case .failed:
                        outputHandle.remove(outputURL)
                        continuation.resume(
                            throwing: exportBox.session.error ?? MediaPipelineError.exportFailed
                        )
                    default:
                        outputHandle.remove(outputURL)
                        continuation.resume(throwing: MediaPipelineError.exportFailed)
                    }
                }
            }
            guard didStart else {
                permit.finishOperation(operationID)
                outputHandle.remove(outputURL)
                continuation.resume(
                    throwing: MediaPipelineError.plaintextProductionInvalidated
                )
                return
            }
        }
    }

    static func makeDeliveryExportSession(
        asset: AVAsset,
        presetName: String,
        outputURL: URL
    ) -> AVAssetExportSession? {
        guard let exportSession = AVAssetExportSession(
            asset: asset,
            presetName: presetName
        ) else {
            return nil
        }

        exportSession.outputURL = outputURL
        exportSession.outputFileType = .mp4
        exportSession.shouldOptimizeForNetworkUse = true
        // AVAssetExportSession copies source metadata by default. The sharing
        // filter removes user-identifying source items such as location. Some
        // formats still preserve their source creation date, so replace that
        // value with a fixed non-source timestamp and write no other metadata.
        let sanitizedCreationDate = AVMutableMetadataItem()
        sanitizedCreationDate.identifier = .quickTimeMetadataCreationDate
        sanitizedCreationDate.value = "1970-01-01T00:00:00Z" as NSString
        sanitizedCreationDate.extendedLanguageTag = "und"
        exportSession.metadataItemFilter = .forSharing()
        exportSession.metadata = [sanitizedCreationDate]
        return exportSession
    }

    func makeThumbnail(
        videoURL: URL,
        identifier: AuthenticatedThumbnailIdentifier,
        permit: ForegroundPlaintextPermit
    ) async throws -> URL {
        try ensureTempRoot()

        let outputURL = localThumbnailURLPath(for: identifier)
        try plaintextTempJanitor.preserveWhileInUse(outputURL)
        var retainFinalOutput = false
        defer {
            if !retainFinalOutput {
                plaintextTempJanitor.release(outputURL)
            }
        }
        if fileManager.fileExists(atPath: outputURL.path) {
            try permit.registerOutput(outputURL)
            retainFinalOutput = true
            return outputURL
        }

        let asset = AVURLAsset(url: videoURL)
        let duration = CMTimeGetSeconds(asset.duration)
        let captureTime = duration.isFinite && duration > 0.2 ? duration - 0.1 : 0
        let generator = AVAssetImageGenerator(asset: asset)
        generator.appliesPreferredTrackTransform = true
        generator.maximumSize = CGSize(width: 640, height: 640)
        generator.requestedTimeToleranceBefore = .zero
        generator.requestedTimeToleranceAfter = .positiveInfinity

        let stagedURL = tempRoot
            .appendingPathComponent("thumbnail-staged-\(UUID().uuidString)")
            .appendingPathExtension("jpg")
        let operationID = try permit.beginOperation(
            outputURLs: [stagedURL, outputURL],
            cancellation: { generator.cancelAllCGImageGeneration() }
        )
        defer { permit.finishOperation(operationID) }

        let cgImage = try generator.copyCGImage(
            at: CMTime(seconds: captureTime, preferredTimescale: 600),
            actualTime: nil
        )
        let image = UIImage(cgImage: cgImage)
        guard let data = image.jpegData(compressionQuality: 0.78) else {
            throw MediaPipelineError.exportFailed
        }

        try plaintextTempJanitor.beginProducing([stagedURL, outputURL])
        defer {
            plaintextTempJanitor.finishProducing([stagedURL, outputURL])
        }
        var createdFinalOutput = false
        do {
            try permit.createOutputs(at: [stagedURL, outputURL]) {
                try data.write(to: stagedURL, options: [.atomic])
                try fileManager.setAttributes(
                    [.protectionKey: FileProtectionType.complete],
                    ofItemAtPath: stagedURL.path
                )
                try fileManager.moveItem(at: stagedURL, to: outputURL)
                createdFinalOutput = true
                plaintextTempJanitor.release(stagedURL)
            }
        } catch {
            removePlaintextTemporaryFile(stagedURL)
            if createdFinalOutput {
                removePlaintextTemporaryFile(outputURL)
            } else if fileManager.fileExists(atPath: outputURL.path), permit.isValid {
                // Another foreground writer won the authenticated destination.
                retainFinalOutput = true
                return outputURL
            }
            throw error
        }
        guard permit.isValid else {
            removePlaintextTemporaryFile(outputURL)
            throw MediaPipelineError.plaintextProductionInvalidated
        }
        retainFinalOutput = true
        return outputURL
    }

    func encryptPackage(
        compressedVideoURL: URL,
        thumbnailURL: URL?,
        recipientEncryptionPublicKey: Data,
        senderUserID: UUID,
        senderDeviceID: UUID,
        senderIdentityDigest: Data,
        recipientUserID: UUID,
        recipientDeviceID: UUID,
        recipientIdentityDigest: Data
    ) async throws -> EncryptedMediaPackage {
        try ensureTempRoot()

        let contentKey = sodium.aead.xchacha20poly1305ietf.key()
        let plaintext = try Data(contentsOf: compressedVideoURL)
        guard let encrypted = sodium.aead.xchacha20poly1305ietf.encrypt(
            message: Array(plaintext),
            secretKey: contentKey
        ) as (authenticatedCipherText: Bytes, nonce: Bytes)? else {
            throw MediaPipelineError.cryptoOperationFailed("Encrypting the media package")
        }
        guard let sealedContentKey = sodium.box.seal(
            message: contentKey,
            recipientPublicKey: Array(recipientEncryptionPublicKey)
        ) else {
            throw MediaPipelineError.cryptoOperationFailed("Sealing the media content key")
        }
        guard let ciphertextHash = sodium.genericHash.hash(
            message: encrypted.authenticatedCipherText,
            outputLength: 32
        ) else {
            throw MediaPipelineError.cryptoOperationFailed("Hashing the encrypted media package")
        }
        var senderContentKey: ContentKeyEnvelope?
        if let senderIdentity = try await keyManager.currentIdentity(),
           senderIdentity.deviceID == nil || senderIdentity.deviceID == senderDeviceID {
            senderContentKey = try await keyManager.encryptContentKey(
                Data(contentKey),
                recipientPublicKey: senderIdentity.encryptionPublicKey
            )
        }

        let packageID = UUID()
        let encryptedBlobURL = tempRoot
            .appendingPathComponent("encrypted-\(packageID.uuidString)")
            .appendingPathExtension("blob")
        let localEncryptedCopyURL = tempRoot
            .appendingPathComponent("local-encrypted-\(packageID.uuidString)")
            .appendingPathExtension("blob")
        let encryptedData = Data(encrypted.authenticatedCipherText)

        try encryptedData.write(to: encryptedBlobURL, options: [.atomic])
        if fileManager.fileExists(atPath: localEncryptedCopyURL.path) {
            try fileManager.removeItem(at: localEncryptedCopyURL)
        }
        try fileManager.copyItem(at: encryptedBlobURL, to: localEncryptedCopyURL)

        let durationSeconds = durationSeconds(for: compressedVideoURL)
        let createdAt = Date(timeIntervalSince1970: floor(Date().timeIntervalSince1970))
        let unsignedEnvelope = MessageEnvelope(
            version: MessageEnvelope.authenticatedVersion,
            senderDeviceID: senderDeviceID,
            recipientDeviceID: recipientDeviceID,
            media: EncryptedMediaDescriptor(
                algorithm: EncryptedMediaDescriptor.xChaCha20Poly1305,
                nonce: Data(encrypted.nonce),
                ciphertextHash: Data(ciphertextHash),
                mimeType: "video/mp4",
                durationSeconds: durationSeconds,
                thumbnail: nil
            ),
            contentKey: ContentKeyEnvelope(
                algorithm: ContentKeyEnvelope.sealedBox,
                encryptedContentKey: Data(sealedContentKey),
                recipientPublicKeyFingerprint: nil
            ),
            senderContentKey: senderContentKey,
            createdAt: createdAt,
            clientMessageID: packageID,
            senderIdentityDigest: senderIdentityDigest,
            recipientIdentityDigest: recipientIdentityDigest,
            authenticationAlgorithm: MessageEnvelope.ed25519Authentication,
            signature: nil
        )
        let envelope = try await messageAuthenticator.authenticate(
            envelope: unsignedEnvelope,
            senderUserID: senderUserID,
            recipientUserID: recipientUserID,
            keyManager: keyManager
        )

        _ = thumbnailURL
        return EncryptedMediaPackage(
            id: packageID,
            messageID: nil,
            envelope: envelope,
            encryptedBlobURL: encryptedBlobURL,
            localEncryptedCopyURL: localEncryptedCopyURL,
            blobSize: encryptedData.count
        )
    }

    func persistOutgoingPackage(
        _ encryptedPackageURL: URL,
        clientMessageID: UUID
    ) async throws -> URL {
        try ensureTempRoot()

        let localURL = localEncryptedPackageURLPath(
            for: .outgoingClientMessage(clientMessageID)
        )
        guard !fileManager.fileExists(atPath: localURL.path) else {
            throw MediaPipelineError.localPackageCollision(clientMessageID)
        }
        do {
            // This identifier was generated locally and is covered by the
            // envelope signature before any relay request begins.
            try fileManager.copyItem(at: encryptedPackageURL, to: localURL)
        } catch {
            if fileManager.fileExists(atPath: localURL.path) {
                throw MediaPipelineError.localPackageCollision(clientMessageID)
            }
            throw error
        }
        do {
            try fileManager.setAttributes(
                [.protectionKey: FileProtectionType.complete],
                ofItemAtPath: localURL.path
            )
        } catch {
            try? fileManager.removeItem(at: localURL)
            throw error
        }
        return localURL
    }

    func localEncryptedPackageURL(for identifier: LocalEncryptedMediaIdentifier) async -> URL? {
        let preferredURL = localEncryptedPackageURLPath(for: identifier)
        if fileManager.fileExists(atPath: preferredURL.path) {
            return preferredURL
        }

        // Only incoming server IDs can address the pre-release receive-cache
        // layout. Outgoing history never falls back from a signed client ID to
        // a relay-selected namespace.
        if case .incomingServerMessage(let messageID) = identifier {
            let legacyLocalURL = localMediaRoot
                .appendingPathComponent("local-message-\(messageID.uuidString)")
                .appendingPathExtension("blob")
            if fileManager.fileExists(atPath: legacyLocalURL.path) {
                return legacyLocalURL
            }

            let legacyReceivedURL = tempRoot
                .appendingPathComponent("received-\(messageID.uuidString)")
                .appendingPathExtension("blob")
            if fileManager.fileExists(atPath: legacyReceivedURL.path) {
                return legacyReceivedURL
            }
        }

        return nil
    }

    func removeLocalEncryptedPackage(for identifier: LocalEncryptedMediaIdentifier) async throws {
        let fileURL = localEncryptedPackageURLPath(for: identifier)
        if fileManager.fileExists(atPath: fileURL.path) {
            try fileManager.removeItem(at: fileURL)
        }
    }

    func localThumbnailURL(for identifier: AuthenticatedThumbnailIdentifier) async -> URL? {
        let url = localThumbnailURLPath(for: identifier)
        return fileManager.fileExists(atPath: url.path) ? url : nil
    }

    func stageReceivedPackage(
        message: Message,
        downloadedBlobURL: URL
    ) async throws -> StagedReceivedMediaPackage {
        try ensureTempRoot()

        let encryptedData = try Data(contentsOf: downloadedBlobURL)
        try validateCiphertext(
            encryptedData,
            envelope: message.envelope,
            operation: "Verifying the downloaded media package"
        )

        let stagingID = UUID()
        let stagedBlobURL = stagedReceivedPackageURLPath(for: stagingID)
        try encryptedData.write(to: stagedBlobURL, options: [.atomic, .completeFileProtection])

        return StagedReceivedMediaPackage(
            id: stagingID,
            messageID: message.id,
            envelope: message.envelope
        )
    }

    func commitStagedReceivedPackage(
        _ stagedPackage: StagedReceivedMediaPackage,
        allowExistingExactRecovery: Bool
    ) async throws -> EncryptedMediaPackage {
        try ensureTempRoot()

        let stagedBlobURL = stagedReceivedPackageURLPath(for: stagedPackage.id)
        guard fileManager.fileExists(atPath: stagedBlobURL.path) else {
            throw MediaPipelineError.stagedPackageMissing
        }

        let encryptedData = try Data(contentsOf: stagedBlobURL)
        try validateCiphertext(
            encryptedData,
            envelope: stagedPackage.envelope,
            operation: "Verifying the staged media package"
        )

        let localEncryptedCopyURL = localEncryptedPackageURLPath(
            for: .incomingServerMessage(stagedPackage.messageID)
        )
        if fileManager.fileExists(atPath: localEncryptedCopyURL.path) {
            return try recoverExistingPackage(
                stagedPackage: stagedPackage,
                stagedBlobURL: stagedBlobURL,
                stagedData: encryptedData,
                localEncryptedCopyURL: localEncryptedCopyURL,
                allowExistingExactRecovery: allowExistingExactRecovery
            )
        }

        do {
            // FileManager's move has no replace-existing mode. A concurrent
            // writer therefore wins without either package being deleted.
            try fileManager.moveItem(at: stagedBlobURL, to: localEncryptedCopyURL)
        } catch {
            if fileManager.fileExists(atPath: localEncryptedCopyURL.path) {
                return try recoverExistingPackage(
                    stagedPackage: stagedPackage,
                    stagedBlobURL: stagedBlobURL,
                    stagedData: encryptedData,
                    localEncryptedCopyURL: localEncryptedCopyURL,
                    allowExistingExactRecovery: allowExistingExactRecovery
                )
            }
            throw error
        }

        return EncryptedMediaPackage(
            id: stagedPackage.messageID,
            messageID: stagedPackage.messageID,
            envelope: stagedPackage.envelope,
            encryptedBlobURL: localEncryptedCopyURL,
            localEncryptedCopyURL: localEncryptedCopyURL,
            blobSize: encryptedData.count
        )
    }

    private func recoverExistingPackage(
        stagedPackage: StagedReceivedMediaPackage,
        stagedBlobURL: URL,
        stagedData: Data,
        localEncryptedCopyURL: URL,
        allowExistingExactRecovery: Bool
    ) throws -> EncryptedMediaPackage {
        guard allowExistingExactRecovery else {
            throw MediaPipelineError.localPackageCollision(stagedPackage.messageID)
        }

        let existingData = try Data(contentsOf: localEncryptedCopyURL)
        try validateCiphertext(
            existingData,
            envelope: stagedPackage.envelope,
            operation: "Verifying the recovered local media package"
        )
        guard existingData == stagedData else {
            throw MediaPipelineError.localPackageCollision(stagedPackage.messageID)
        }
        if fileManager.fileExists(atPath: stagedBlobURL.path) {
            try fileManager.removeItem(at: stagedBlobURL)
        }

        return EncryptedMediaPackage(
            id: stagedPackage.messageID,
            messageID: stagedPackage.messageID,
            envelope: stagedPackage.envelope,
            encryptedBlobURL: localEncryptedCopyURL,
            localEncryptedCopyURL: localEncryptedCopyURL,
            blobSize: existingData.count
        )
    }

    func discardStagedReceivedPackage(_ stagedPackage: StagedReceivedMediaPackage) async {
        let stagedBlobURL = stagedReceivedPackageURLPath(for: stagedPackage.id)
        do {
            if fileManager.fileExists(atPath: stagedBlobURL.path) {
                try fileManager.removeItem(at: stagedBlobURL)
            }
        } catch {
            assertionFailure("Staged media cleanup failed for \(stagedBlobURL.path): \(error)")
        }
    }

    func validateEncryptedPackage(_ package: EncryptedMediaPackage) async throws {
        let encryptedURL = fileManager.fileExists(atPath: package.localEncryptedCopyURL.path)
            ? package.localEncryptedCopyURL
            : package.encryptedBlobURL
        let encryptedData = try Data(contentsOf: encryptedURL)
        try validateCiphertext(
            encryptedData,
            envelope: package.envelope,
            operation: "Verifying the signed media package"
        )
    }

    func decryptForPlayback(
        package: EncryptedMediaPackage,
        permit: PlaybackPreparationPermit
    ) async throws -> PlaybackTempFile {
        try ensureTempRoot()

        guard permit.isValid else {
            throw MediaPipelineError.playbackPreparationInvalidated
        }

        let encryptedURL = fileManager.fileExists(atPath: package.localEncryptedCopyURL.path)
            ? package.localEncryptedCopyURL
            : package.encryptedBlobURL
        let encryptedData = try Data(contentsOf: encryptedURL)
        try validateCiphertext(
            encryptedData,
            envelope: package.envelope,
            operation: "Verifying the signed media package"
        )

        let contentKey = try await keyManager.decryptContentKey(from: package.envelope.contentKey)

        guard permit.isValid else {
            throw MediaPipelineError.playbackPreparationInvalidated
        }

        guard let plaintext = sodium.aead.xchacha20poly1305ietf.decrypt(
            authenticatedCipherText: Array(encryptedData),
            secretKey: Array(contentKey),
            nonce: Array(package.envelope.media.nonce)
        ) else {
            throw MediaPipelineError.cryptoOperationFailed("Decrypting the media package")
        }

        let outputURL = tempRoot
            .appendingPathComponent("playback-\(UUID().uuidString)")
            .appendingPathExtension("mp4")
        try plaintextTempJanitor.beginProducing([outputURL])
        defer { plaintextTempJanitor.finishProducing([outputURL]) }
        do {
            try permit.createOutput(at: outputURL) {
                try Data(plaintext).write(to: outputURL, options: [.atomic])
                try fileManager.setAttributes(
                    [.protectionKey: FileProtectionType.complete],
                    ofItemAtPath: outputURL.path
                )
            }
        } catch {
            removePlaintextTemporaryFile(outputURL)
            throw error
        }

        return PlaybackTempFile(
            id: UUID(),
            url: outputURL,
            createdAt: Date(),
            cleanupDeadline: Date().addingTimeInterval(15 * 60)
        )
    }

    func cleanupTemporaryFiles(_ urls: [URL]) async {
        var visitedPaths: Set<String> = []
        for url in urls {
            let canonicalURL = url.standardizedFileURL
            guard visitedPaths.insert(canonicalURL.path).inserted else {
                continue
            }
            guard isOwnedTemporaryOrLocalMediaURL(canonicalURL) else {
                assertionFailure("Refusing to delete media outside Kithra-owned roots: \(canonicalURL.path)")
                continue
            }

            plaintextTempJanitor.release(canonicalURL)
            do {
                guard fileManager.fileExists(atPath: canonicalURL.path) else {
                    continue
                }
                let values = try canonicalURL.resourceValues(forKeys: [
                    .isRegularFileKey,
                    .isSymbolicLinkKey
                ])
                guard values.isRegularFile == true, values.isSymbolicLink != true else {
                    assertionFailure("Refusing to delete non-regular media: \(canonicalURL.path)")
                    continue
                }
                try fileManager.removeItem(at: canonicalURL)
            } catch {
                assertionFailure("Media cleanup failed for \(canonicalURL.path): \(error)")
            }
        }
    }

    func removePlaintextTemporaryFiles(_ urls: [URL]) async throws {
        var failedPaths: [String] = []
        var visitedPaths: Set<String> = []
        for url in urls {
            let canonicalURL = url.standardizedFileURL
            guard visitedPaths.insert(canonicalURL.path).inserted else {
                continue
            }

            guard KithraPlaintextTempFileJanitor.ownsPlaintextFile(
                canonicalURL,
                applicationTemporaryRoot: fileManager.temporaryDirectory,
                mediaTemporaryRoot: tempRoot
            ) else {
                failedPaths.append(canonicalURL.path)
                continue
            }

            plaintextTempJanitor.release(canonicalURL)
            do {
                if fileManager.fileExists(atPath: canonicalURL.path) {
                    let values = try canonicalURL.resourceValues(forKeys: [
                        .isRegularFileKey,
                        .isSymbolicLinkKey
                    ])
                    guard values.isRegularFile == true,
                          values.isSymbolicLink != true else {
                        failedPaths.append(canonicalURL.path)
                        continue
                    }
                    try fileManager.removeItem(at: canonicalURL)
                }
            } catch {
                failedPaths.append(canonicalURL.path)
            }
        }

        if !failedPaths.isEmpty {
            throw PlaintextTemporaryFileCleanupError(failedPaths: failedPaths)
        }
    }

    func cleanupAbandonedPlaintextTemporaryFiles() async {
        _ = plaintextTempJanitor.cleanupAbandonedFiles(
            fileManager: fileManager,
            applicationTemporaryRoot: fileManager.temporaryDirectory,
            mediaTemporaryRoot: tempRoot
        )
    }

    func closePlaintextProductionForAccountDeletion() {
        plaintextTempJanitor.closeForAccountDeletion()
    }

    func reopenPlaintextProductionAfterAccountDeletionEnds() {
        plaintextTempJanitor.reopenAfterAccountDeletionEnds()
    }

    func removeAbandonedPlaintextTemporaryFilesForAccountDeletion() async throws {
        guard plaintextTempJanitor.accountDeletionBarrierIsClosed else {
            throw MediaPipelineError.plaintextProductionInvalidated
        }
        let report = plaintextTempJanitor.cleanupAbandonedFiles(
            fileManager: fileManager,
            applicationTemporaryRoot: fileManager.temporaryDirectory,
            mediaTemporaryRoot: tempRoot
        )
        let unresolvedFiles = report.failedFiles + report.activeFiles
        guard unresolvedFiles.isEmpty else {
            throw PlaintextTemporaryFileCleanupError(
                failedPaths: unresolvedFiles.map(\.path)
            )
        }
    }

    func removeAllLocalMedia() async throws {
        if fileManager.fileExists(atPath: tempRoot.path) {
            try fileManager.removeItem(at: tempRoot)
        }
        if fileManager.fileExists(atPath: localMediaRoot.path) {
            try fileManager.removeItem(at: localMediaRoot)
        }
    }

    private func ensureTempRoot() throws {
        if !fileManager.fileExists(atPath: tempRoot.path) {
            try fileManager.createDirectory(at: tempRoot, withIntermediateDirectories: true, attributes: nil)
        }
        if !fileManager.fileExists(atPath: incomingStagingRoot.path) {
            try fileManager.createDirectory(
                at: incomingStagingRoot,
                withIntermediateDirectories: true,
                attributes: [.protectionKey: FileProtectionType.complete]
            )
        }
        if !fileManager.fileExists(atPath: localMediaRoot.path) {
            try fileManager.createDirectory(
                at: localMediaRoot,
                withIntermediateDirectories: true,
                attributes: [.protectionKey: FileProtectionType.complete]
            )
            var values = URLResourceValues()
            values.isExcludedFromBackup = true
            var mutableLocalMediaRoot = localMediaRoot
            try? mutableLocalMediaRoot.setResourceValues(values)
        }
    }

    private func removePlaintextTemporaryFile(_ url: URL) {
        plaintextTempJanitor.release(url)
        if fileManager.fileExists(atPath: url.path) {
            try? fileManager.removeItem(at: url)
        }
    }

    private func isOwnedTemporaryOrLocalMediaURL(_ url: URL) -> Bool {
        isDescendant(url, of: fileManager.temporaryDirectory)
            || isDescendant(url, of: tempRoot)
            || isDescendant(url, of: localMediaRoot)
    }

    private func isDescendant(_ url: URL, of root: URL) -> Bool {
        let urlComponents = url.standardizedFileURL.pathComponents
        let rootComponents = root.standardizedFileURL.pathComponents
        guard urlComponents.count > rootComponents.count else {
            return false
        }
        return Array(urlComponents.prefix(rootComponents.count)) == rootComponents
    }

    private func localEncryptedPackageURLPath(
        for identifier: LocalEncryptedMediaIdentifier
    ) -> URL {
        let component: String
        switch identifier {
        case .outgoingClientMessage(let clientMessageID):
            component = "outgoing-client-\(clientMessageID.uuidString)"
        case .incomingServerMessage(let serverMessageID):
            component = "incoming-server-\(serverMessageID.uuidString)"
        }
        return localMediaRoot
            .appendingPathComponent(component)
            .appendingPathExtension("blob")
    }

    private func localThumbnailURLPath(
        for identifier: AuthenticatedThumbnailIdentifier
    ) -> URL {
        // Thumbnails reveal video content, so keep them with short-lived
        // plaintext artifacts rather than persistent encrypted history.
        let authorityComponent: String
        switch identifier.authority {
        case .outgoingClientMessage(let clientMessageID):
            authorityComponent = "outgoing-client-\(clientMessageID.uuidString)"
        case .incomingServerMessage(let serverMessageID):
            authorityComponent = "incoming-server-\(serverMessageID.uuidString)"
        }
        let signatureHex = identifier.envelopeSignature
            .map { String(format: "%02x", $0) }
            .joined()
        return tempRoot
            .appendingPathComponent("thumb-\(authorityComponent)-auth-\(signatureHex)")
            .appendingPathExtension("jpg")
    }

    private func stagedReceivedPackageURLPath(for stagingID: UUID) -> URL {
        incomingStagingRoot
            .appendingPathComponent("incoming-\(stagingID.uuidString)")
            .appendingPathExtension("blob")
    }

    private func validateCiphertext(
        _ encryptedData: Data,
        envelope: MessageEnvelope,
        operation: String
    ) throws {
        guard let expectedHash = envelope.media.ciphertextHash,
              expectedHash.count == 32,
              let actualHash = sodium.genericHash.hash(
                  message: Array(encryptedData),
                  outputLength: 32
              ),
              sodium.utils.equals(actualHash, Array(expectedHash)) else {
            throw MediaPipelineError.cryptoOperationFailed(operation)
        }
    }

    private func durationSeconds(for videoURL: URL) -> Double? {
        let seconds = CMTimeGetSeconds(AVURLAsset(url: videoURL).duration)
        guard seconds.isFinite, seconds > 0 else {
            return nil
        }
        return seconds
    }
}

private final class SendableExportSession: @unchecked Sendable {
    let session: AVAssetExportSession

    init(_ session: AVAssetExportSession) {
        self.session = session
    }
}

/// A narrowly scoped cross-thread handle for an exact plaintext output. The
/// wrapped janitor is lock protected and FileManager's per-call operations are
/// safe here; keeping this handle separate avoids treating the full media
/// pipeline (including key-management state) as Sendable.
private final class PlaintextOutputFileHandle: @unchecked Sendable {
    private let fileManager: FileManager
    private let plaintextTempJanitor: KithraPlaintextTempFileJanitor

    init(
        fileManager: FileManager,
        plaintextTempJanitor: KithraPlaintextTempFileJanitor
    ) {
        self.fileManager = fileManager
        self.plaintextTempJanitor = plaintextTempJanitor
    }

    func applyCompleteProtection(to url: URL) throws {
        try fileManager.setAttributes(
            [.protectionKey: FileProtectionType.complete],
            ofItemAtPath: url.path
        )
    }

    func remove(_ url: URL) {
        plaintextTempJanitor.release(url)
        if fileManager.fileExists(atPath: url.path) {
            try? fileManager.removeItem(at: url)
        }
    }
}
